using System.Collections.Generic;
using System.Linq;

using SHCDESE.Interop;

namespace SHCDESE.API;

/// <summary>
/// Contains some utility to get the proper building scale sizes, given the eMappers value describing the object.
/// </summary>
public static class BuildingScales
{
    public static readonly IReadOnlyDictionary<eMappers, int> ScaleByMapper =
        new Dictionary<eMappers, int>
        {
            // Scale 0 - Flags, People, Assembly Points, Markers
            { eMappers.MAPPER_FLAG_TYPE0,                    0 },
            { eMappers.MAPPER_FLAG_TYPE1,                    0 },
            { eMappers.MAPPER_FLAG_TYPE2,                    0 },
            { eMappers.MAPPER_FLAG_TYPE3,                    0 },
            { eMappers.MAPPER_HEADS,                         0 },
            { eMappers.MAPPER_BRAZIER,                       0 },
            { eMappers.MAPPER_MANGONEL,                      0 },
            { eMappers.MAPPER_BALLISTA,                      0 },
            { eMappers.MAPPER_PEOPLE_ARCHERS,                0 },
            { eMappers.MAPPER_PEOPLE_SPEARMEN,               0 },
            { eMappers.MAPPER_PEOPLE_PIKEMEN,                0 },
            { eMappers.MAPPER_PEOPLE_MACEMEN,                0 },
            { eMappers.MAPPER_PEOPLE_XBOWMEN,                0 },
            { eMappers.MAPPER_PEOPLE_SWORDSMEN,              0 },
            { eMappers.MAPPER_PEOPLE_KNIGHTS,                0 },
            { eMappers.MAPPER_PEOPLE_LADDERMEN,              0 },
            { eMappers.MAPPER_PEOPLE_ENGINEERS,              0 },
            { eMappers.MAPPER_PEOPLE_ENGINEERS_POTS,         0 },
            { eMappers.MAPPER_PEOPLE_MONKS,                  0 },
            { eMappers.MAPPER_PEOPLE_CATAPULTS,              0 },
            { eMappers.MAPPER_PEOPLE_TREBUCHETS,             0 },
            { eMappers.MAPPER_PEOPLE_BATTERING_RAMS,         0 },
            { eMappers.MAPPER_PEOPLE_SIEGE_TOWERS,           0 },
            { eMappers.MAPPER_PEOPLE_PORTABLE_SHIELDS,       0 },
            { eMappers.MAPPER_PEOPLE_TUNNELERS,              0 },
            { eMappers.MAPPER_PLACE_ASSEMBLY_POINT1,         0 },
            { eMappers.MAPPER_PLACE_ASSEMBLY_POINT2,         0 },
            { eMappers.MAPPER_PLACE_ASSEMBLY_POINT3,         0 },
            { eMappers.MAPPER_PLACE_ASSEMBLY_POINT4,         0 },
            { eMappers.MAPPER_PLACE_ASSEMBLY_POINT5,         0 },
            { eMappers.MAPPER_PLACE_ASSEMBLY_POINT6,         0 },
            { eMappers.MAPPER_PLACE_ASSEMBLY_POINT7,         0 },
            { eMappers.MAPPER_PEOPLE_ARAB_BOW,               0 },
            { eMappers.MAPPER_PEOPLE_ARAB_SLAVE,             0 },
            { eMappers.MAPPER_PEOPLE_ARAB_SLINGER,           0 },
            { eMappers.MAPPER_PEOPLE_ARAB_ASSASIN,           0 },
            { eMappers.MAPPER_PEOPLE_ARAB_HORSEMAN,          0 },
            { eMappers.MAPPER_PEOPLE_ARAB_SWORDSMAN,         0 },
            { eMappers.MAPPER_PEOPLE_ARAB_GRENADIER,         0 },
            { eMappers.MAPPER_PEOPLE_ARAB_BALLISTA,          0 },
            { eMappers.MAPPER_PLACE_ASSEMBLY_POINTM1,        0 },
            { eMappers.MAPPER_PLACE_ASSEMBLY_POINTM2,        0 },
            { eMappers.MAPPER_PLACE_ASSEMBLY_POINTM3,        0 },
            { eMappers.MAPPER_PLACE_ASSEMBLY_POINTM4,        0 },
            { eMappers.MAPPER_PLACE_ASSEMBLY_POINTM5,        0 },
            { eMappers.MAPPER_PLACE_ASSEMBLY_POINTM6,        0 },
            { eMappers.MAPPER_PLACE_ASSEMBLY_POINTM7,        0 },
            { eMappers.MAPPER_PLACE_ASSEMBLY_POINTE1,        0 },
            { eMappers.MAPPER_PLACE_ASSEMBLY_POINTE2,        0 },
            { eMappers.MAPPER_PLACE_ASSEMBLY_POINTT1,        0 },
            { eMappers.MAPPER_PLACE_ASSEMBLY_POINTK1,        0 },
            { eMappers.MAPPER_MARKER_POINT1,                 0 },
            { eMappers.MAPPER_MARKER_POINT2,                 0 },
            { eMappers.MAPPER_MARKER_POINT3,                 0 },
            { eMappers.MAPPER_MARKER_POINT4,                 0 },
            { eMappers.MAPPER_MARKER_POINT5,                 0 },
            { eMappers.MAPPER_MARKER_POINT6,                 0 },
            { eMappers.MAPPER_MARKER_POINT7,                 0 },
            { eMappers.MAPPER_MARKER_POINT8,                 0 },
            { eMappers.MAPPER_MARKER_POINT9,                 0 },
            { eMappers.MAPPER_MARKER_POINT10,                0 },
            { eMappers.MAPPER_PLACE_ASSEMBLY_POINTBS1,       0 },
            { eMappers.MAPPER_PLACE_ASSEMBLY_POINTBS2,       0 },
            { eMappers.MAPPER_PLACE_ASSEMBLY_POINTBS3,       0 },
            { eMappers.MAPPER_PLACE_ASSEMBLY_POINTBS4,       0 },
            { eMappers.MAPPER_PLACE_ASSEMBLY_POINTBS5,       0 },
            { eMappers.MAPPER_PLACE_ASSEMBLY_POINTBS6,       0 },
            { eMappers.MAPPER_PLACE_ASSEMBLY_POINTBS7,       0 },
            { eMappers.MAPPER_PLACE_ASSEMBLY_POINTBS8,       0 },
            { eMappers.MAPPER_PEOPLE_BEDOUIN_CAMEL_LANCER,   0 },
            { eMappers.MAPPER_PEOPLE_BEDOUIN_HEALER,         0 },
            { eMappers.MAPPER_PEOPLE_BEDOUIN_EUNUCH,         0 },
            { eMappers.MAPPER_PEOPLE_BEDOUIN_AMBUSHER,       0 },
            { eMappers.MAPPER_PEOPLE_BEDOUIN_SKIRMISHER,     0 },
            { eMappers.MAPPER_PEOPLE_BEDOUIN_HEAVY_CAMEL,    0 },
            { eMappers.MAPPER_PEOPLE_BEDOUIN_SAPPER,         0 },
            { eMappers.MAPPER_PEOPLE_BEDOUIN_DEMOLISHER,     0 },

            // Scale 1 - Small ground features
            { eMappers.MAPPER_CAMP_FIRE,                     1 },
            { eMappers.MAPPER_KILLING_PIT,                   1 },
            { eMappers.MAPPER_PITCH_DITCH,                   1 },
            { eMappers.MAPPER_SHRINE5,                       1 },
            { eMappers.MAPPER_RUINS1,                        1 },
            { eMappers.MAPPER_RUINS2,                        1 },
            { eMappers.MAPPER_RUINS3,                        1 },
            { eMappers.MAPPER_RUINS4,                        1 },
            { eMappers.MAPPER_RUINS23,                       1 },
            { eMappers.MAPPER_RUINS24,                       1 },
            { eMappers.MAPPER_RUINS25,                       1 },
            { eMappers.MAPPER_RUINS26,                       1 },
            { eMappers.MAPPER_RUINS27,                       1 },
            { eMappers.MAPPER_RUINS28,                       1 },

            // Scale 2 - Small decorations, moats, gardens, statues
            { eMappers.MAPPER_UNDUGMOAT,                     2 },
            { eMappers.MAPPER_DUGMOAT,                       2 },
            { eMappers.MAPPER_MOAT,                          2 },
            { eMappers.MAPPER_ANTIMOAT,                      2 },
            { eMappers.MAPPER_OXENBASE,                      2 },
            { eMappers.MAPPER_SIGNPOST,                      2 },
            { eMappers.MAPPER_GATE_POSTERN,                  2 },
            { eMappers.MAPPER_GARDEN1,                       2 },
            { eMappers.MAPPER_GARDEN2,                       2 },
            { eMappers.MAPPER_GARDEN3,                       2 },
            { eMappers.MAPPER_GARDEN4,                       2 },
            { eMappers.MAPPER_GARDEN5,                       2 },
            { eMappers.MAPPER_GARDEN6,                       2 },
            { eMappers.MAPPER_GALLOWS,                       2 },
            { eMappers.MAPPER_GIBBET,                        2 },
            { eMappers.MAPPER_STATUE1,                       2 },
            { eMappers.MAPPER_STATUE2,                       2 },
            { eMappers.MAPPER_STATUE3,                       2 },
            { eMappers.MAPPER_STATUE4,                       2 },
            { eMappers.MAPPER_STATUE5,                       2 },
            { eMappers.MAPPER_SHRINE1,                       2 },
            { eMappers.MAPPER_SHRINE2,                       2 },
            { eMappers.MAPPER_SHRINE3,                       2 },
            { eMappers.MAPPER_SHRINE4,                       2 },
            { eMappers.MAPPER_RUINS5,                        2 },
            { eMappers.MAPPER_RUINS6,                        2 },
            { eMappers.MAPPER_RUINS7,                        2 },
            { eMappers.MAPPER_RUINS8,                        2 },
            { eMappers.MAPPER_RUINS9,                        2 },
            { eMappers.MAPPER_RUINS10,                       2 },

            // Scale 3 - Small-medium buildings & siege equipment
            { eMappers.MAPPER_WOODSMAN,                      3 },
            { eMappers.MAPPER_TUNNEL,                        3 },
            { eMappers.MAPPER_TUNNEL_CONSTRUCTION,           3 },
            { eMappers.MAPPER_MILL,                          3 },
            { eMappers.MAPPER_HUNTER,                        3 },
            { eMappers.MAPPER_TOWER1,                        3 },
            { eMappers.MAPPER_GATE_WOOD1A,                   3 },
            { eMappers.MAPPER_GATE_WOOD1B,                   3 },
            { eMappers.MAPPER_GATE_WOOD1C,                   3 },
            { eMappers.MAPPER_GATE_WOOD1D,                   3 },
            { eMappers.MAPPER_GARDEN7,                       3 },
            { eMappers.MAPPER_GARDEN8,                       3 },
            { eMappers.MAPPER_GARDEN9,                       3 },
            { eMappers.MAPPER_MAYPOLE,                       3 },
            { eMappers.MAPPER_STOCKS,                        3 },
            { eMappers.MAPPER_CATAPULT,                      3 },
            { eMappers.MAPPER_TREBUCHET,                     3 },
            { eMappers.MAPPER_SIEGE_TOWER,                   3 },
            { eMappers.MAPPER_BATTERING_RAM,                 3 },
            { eMappers.MAPPER_PORTABLE_SHIELD,               3 },
            { eMappers.MAPPER_BURNING_STAKE,                 3 },
            { eMappers.MAPPER_RACK_STRETCHING,               3 },
            { eMappers.MAPPER_CHOPPING_BLOCK,                3 },
            { eMappers.MAPPER_DOG_CAGE,                      3 },
            { eMappers.MAPPER_WELL,                          3 },
            { eMappers.MAPPER_ARAB_BALLISTA,                 3 },
            { eMappers.MAPPER_RUINS22,                       3 },
            { eMappers.MAPPER_RUINS33,                       3 },

            // Scale 4 - Medium industry buildings
            { eMappers.MAPPER_FLETCHER,                      4 },
            { eMappers.MAPPER_HOVEL,                         4 },
            { eMappers.MAPPER_BAKER,                         4 },
            { eMappers.MAPPER_BREWER,                        4 },
            { eMappers.MAPPER_GRANARY,                       4 },
            { eMappers.MAPPER_ARMOURY,                       4 },
            { eMappers.MAPPER_POLETURNER,                    4 },
            { eMappers.MAPPER_BLACKSMITH,                    4 },
            { eMappers.MAPPER_ARMOURER,                      4 },
            { eMappers.MAPPER_TANNER,                        4 },
            { eMappers.MAPPER_IRON_MINE,                     4 },
            { eMappers.MAPPER_PITCH_WORKINGS,                4 },
            { eMappers.MAPPER_TOWER2,                        4 },
            { eMappers.MAPPER_GARDEN10,                      4 },
            { eMappers.MAPPER_GARDEN11,                      4 },
            { eMappers.MAPPER_GARDEN12,                      4 },
            { eMappers.MAPPER_OIL_SMELTER,                   4 },
            { eMappers.MAPPER_WATERPOT,                      4 },
            { eMappers.MAPPER_RUINS11,                       4 },
            { eMappers.MAPPER_RUINS12,                       4 },
            { eMappers.MAPPER_RUINS13,                       4 },
            { eMappers.MAPPER_RUINS29,                       4 },

            // Scale 5 - Larger military/civic buildings
            { eMappers.MAPPER_STORES,                        5 },
            { eMappers.MAPPER_OUTPOST_BEDOUIN,               5 },
            { eMappers.MAPPER_TRADEPOST,                     5 },
            { eMappers.MAPPER_BEDOUIN_STOCKADE,              5 },
            { eMappers.MAPPER_BARRACKS_WOOD,                 5 },
            { eMappers.MAPPER_BARRACKS_STONE,                5 },
            { eMappers.MAPPER_ENGINEERS_GUILD,               5 },
            { eMappers.MAPPER_TUNNELERS_GUILD,               5 },
            { eMappers.MAPPER_INN,                           5 },
            { eMappers.MAPPER_GATE_INNER,                    5 },
            { eMappers.MAPPER_DRAWBRIDGE,                    5 },
            { eMappers.MAPPER_TOWER3,                        5 },
            { eMappers.MAPPER_GATE_STONE1A,                  5 },
            { eMappers.MAPPER_GATE_STONE1B,                  5 },
            { eMappers.MAPPER_OUTPOST,                       5 },
            { eMappers.MAPPER_OUTPOST_ARAB,                  5 },
            { eMappers.MAPPER_CESS_PIT1,                     5 },
            { eMappers.MAPPER_CESS_PIT2,                     5 },
            { eMappers.MAPPER_CESS_PIT3,                     5 },
            { eMappers.MAPPER_CESS_PIT4,                     5 },
            { eMappers.MAPPER_DUNGEON,                       5 },
            { eMappers.MAPPER_DUNKING_STOOL,                 5 },
            { eMappers.MAPPER_DANCING_BEAR,                  5 },
            { eMappers.MAPPER_POND1,                         5 },
            { eMappers.MAPPER_POND2,                         5 },
            { eMappers.MAPPER_RUINS19,                       5 },
            { eMappers.MAPPER_RUINS20,                       5 },
            { eMappers.MAPPER_RUINS21,                       5 },
            { eMappers.MAPPER_RUINS30,                       5 },

            // Scale 6 - Large towers, quarry, ravines
            { eMappers.MAPPER_QUARRY,                        6 },
            { eMappers.MAPPER_STABLES,                       6 },
            { eMappers.MAPPER_HEALER,                        6 },
            { eMappers.MAPPER_CHURCH1,                       6 },
            { eMappers.MAPPER_TOWER4,                        6 },
            { eMappers.MAPPER_TOWER5,                        6 },
            { eMappers.MAPPER_POND3,                         6 },
            { eMappers.MAPPER_POND4,                         6 },
            { eMappers.MAPPER_RUINS16,                       6 },
            { eMappers.MAPPER_RUINS31,                       6 },
            { eMappers.MAPPER_RUINS32,                       6 },
            { eMappers.MAPPER_POND9_RAVINE1A,                6 },
            { eMappers.MAPPER_POND10_RAVINE1B,               6 },
            { eMappers.MAPPER_POND11_RAVINE1C,               6 },
            { eMappers.MAPPER_POND12_RAVINE1AR,              6 },
            { eMappers.MAPPER_POND13_RAVINE1BR,              6 },
            { eMappers.MAPPER_POND14_RAVINE1CR,              6 },
            { eMappers.MAPPER_POND15_RAVINE2A,               6 },
            { eMappers.MAPPER_POND16_RAVINE2B,               6 },
            { eMappers.MAPPER_POND17_RAVINE2C,               6 },
            { eMappers.MAPPER_POND18_RAVINE2AR,              6 },
            { eMappers.MAPPER_POND19_RAVINE2BR,              6 },
            { eMappers.MAPPER_POND20_RAVINE2CR,              6 },

            // Scale 7 - Keeps, main gate, docks
            { eMappers.MAPPER_KEEP1,                         7 },
            { eMappers.MAPPER_KEEP2,                         7 },
            { eMappers.MAPPER_GATE_MAIN,                     7 },
            { eMappers.MAPPER_GATE_STONE2A,                  7 },
            { eMappers.MAPPER_GATE_STONE2B,                  7 },
            { eMappers.MAPPER_DOCK,                          7 },
            { eMappers.MAPPER_DOCK2,                         7 },
            { eMappers.MAPPER_DOCK3,                         7 },
            { eMappers.MAPPER_DOCK4,                         7 },
            { eMappers.MAPPER_RUINS18,                       7 },

            // Scale 8
            { eMappers.MAPPER_POND5,                         8 },
            { eMappers.MAPPER_POND6,                         8 },

            // Scale 9 - Large farms, big church
            { eMappers.MAPPER_WHEATFARM,                     9 },
            { eMappers.MAPPER_HOPSFARM,                      9 },
            { eMappers.MAPPER_CHURCH2,                       9 },
            { eMappers.MAPPER_POND7,                         9 },
            { eMappers.MAPPER_POND8,                         9 },

            // Scale 10 - Largest farms
            { eMappers.MAPPER_APPLEFARM,                     10 },
            { eMappers.MAPPER_CATTLEFARM,                    10 },

            // Scale 11 - Largest keep, big ruins
            { eMappers.MAPPER_KEEP3,                         11 },
            { eMappers.MAPPER_RUINS14,                       11 },
            { eMappers.MAPPER_RUINS15,                       11 },
            { eMappers.MAPPER_RUINS17,                       11 },

            // Scale 13 - Cathedral, largest ruin
            { eMappers.MAPPER_CHURCH3,                       13 },
            { eMappers.MAPPER_RUINS34,                       13 },
        };

    /// <summary>
    /// Returns the scale for the given mapper, or -1 if not found.
    /// </summary>
    public static int GetScale(eMappers mapper) => ScaleByMapper.TryGetValue(mapper, out int scale) ? scale : -1;

    /// <summary>
    /// Returns all mappers that have the given scale value.
    /// </summary>
    public static IEnumerable<eMappers> GetMappersAtScale(int scale) => ScaleByMapper.Where(kvp => kvp.Value == scale).Select(kvp => kvp.Key);
}