using SHCDESE.API;
using SHCDESE.API.Components.Sprite;
using SHCDESE.Logging;
using System;
using UnityEngine;

namespace SHCDESE.ManagedHooks;

public partial class ManagedHookManager
{
    //
    // SpriteMapping
    //
    internal ManagedDetour<SpriteMapping_SetBodySprite_delegate> spriteMapping_SetBodySprite_hook;
    internal delegate void SpriteMapping_SetBodySprite_delegate(SpriteRenderer renderer, int file, int image, int colour, bool altFrame, int chopFeet, int transparency);
    internal void SpriteMapping_SetBodySprite_Hook(SpriteRenderer renderer, int file, int image, int colour, bool altFrame, int chopFeet, int transparency)
    {
        spriteMapping_SetBodySprite_hook.Trampoline(renderer, file, image, colour, altFrame, chopFeet, transparency);
        try
        {
            if (renderer == null || renderer.sprite == null)
                return;

            // Check if this sprite has a custom material generated by us
            int spriteId = renderer.sprite.GetInstanceID();
            if (GameSpriteManagerAPI.Instance.TryGetCustomMaterials(spriteId, out Material[]? customMaterials, out SpriteMaterialMode materialMode) && customMaterials != null && customMaterials.Length > 0)
            {
                int materialIndex = 0;
                if (chopFeet > 0)
                {
                    materialIndex = chopFeet / 4;
                    if (materialIndex > 6)
                        materialIndex = 6;
                }

                if (materialIndex >= customMaterials.Length)
                    materialIndex = customMaterials.Length - 1;

                // The cache has the same seven-slot layout as vanilla: seven cutoff materials for TeamColour and repeated shared entries for Foliage/Plain.
                renderer.sharedMaterial = customMaterials[materialIndex];

                GameSpriteManagerAPI.ApplyCustomMaterialColour(renderer, file, colour, transparency, materialMode);
            }
        }
        catch (Exception ex)
        {
            LogHelper.Error(ex, "Failed to apply an individual sprite override material.");
        }
    }
}
